# source 'http://rubygems.org'
source 'http://ruby.taobao.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'builder', '~> 3.0.0'
gem 'activerecord', '~> 3.2.0'
gem 'sinatra-partial'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'sqlite3'
gem 'haml'
gem 'pg'
gem 'mysql2'
gem 'sphinx'
gem 'rsolr'
gem 'sunspot'
gem 'tire'
gem 'rubberband'
gem 'stretcher'

group :development do
  gem 'rake'
  gem 'racksh'
  gem 'shotgun'
  gem 'tux'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'rubocop'
  gem 'guard-rubocop'
  gem 'simplecov'
end
